const heroRoles = {
  BLAZE: 'Warrior',
  GARROSH: 'Warrior',
  'D.VA': 'Warrior',
  VARIAN: 'Warrior',
  ZARYA: 'Warrior',
  DEHAKA: 'Warrior',
  CHO: 'Warrior',
  ARTANIS: 'Warrior',
  REXXAR: 'Warrior',
  LEORIC: 'Warrior',
  JOHANNA: 'Warrior',
  'ANUB\'ARAK': 'Warrior',
  CHEN: 'Warrior',
  DIABLO: 'Warrior',
  TYRAEL: 'Warrior',
  SONYA: 'Warrior',
  'E.T.C': 'Warrior',
  MURADIN: 'Warrior',
  STITCHES: 'Warrior',
  ARTHAS: 'Warrior',
  FENIX: 'Assassin',
  MAIEV: 'Assassin',
  HANZO: 'Assassin',
  JUNKRAT: 'Assassin',
  'KEL\'THUZAD': 'Assassin',
  MALTHAEL: 'Assassin',
  GENJI: 'Assassin',
  CASSIA: 'Assassin',
  VALEERA: 'Assassin',
  'ZUL\'JIN': 'Assassin',
  RAGNAROS: 'Assassin',
  SAMURO: 'Assassin',
  ALARAK: 'Assassin',
  'GUL\'DAN': 'Assassin',
  CHROMIE: 'Assassin',
  TRACER: 'Assassin',
  'LI-MING': 'Assassin',
  GREYMANE: 'Assassin',
  LUNARA: 'Assassin',
  GALL: 'Assassin',
  'THE BUTCHER': 'Assassin',
  'KAEL\'THAS': 'Assassin',
  THRALL: 'Assassin',
  JAINA: 'Assassin',
  TYCHUS: 'Assassin',
  ZERATUL: 'Assassin',
  ILLIDAN: 'Assassin',
  RAYNOR: 'Assassin',
  KERRIGAN: 'Assassin',
  VALLA: 'Assassin',
  NOVA: 'Assassin',
  FALSTAD: 'Assassin',
  DECAKRD: 'Support',
  ALEXSTRASZA: 'Support',
  ANA: 'Support',
  STUKOV: 'Support',
  'LÚCIO': 'Support',
  AURIEL: 'Support',
  'LT. MORALES': 'Support',
  KHARAZIM: 'Support',
  REHGAR: 'Support',
  BRIGHTWING: 'Support',
  'LI LI': 'Support',
  TASSADAR: 'Support',
  UTHER: 'Support',
  MALFURION: 'Support',
  TYRANDE: 'Support',
  PROBIUS: 'Specialist',
  MEDIVH: 'Specialist',
  XUL: 'Specialist',
  SYLVANAS: 'Specialist',
  'THE LOST VIKINGS': 'Specialist',
  AZMODAN: 'Specialist',
  ZAGARA: 'Specialist',
  MURKY: 'Specialist',
  'SGT. HAMMER': 'Specialist',
  NAZEEBO: 'Specialist',
  GAZLOWE: 'Specialist',
  ABATHUR: 'Specialist'
}

module.exports = heroRoles
